name: CI - Secrets

on:
  push:
    branches: [ main ]
  
jobs:
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2
    - name: Set Secrets
      run: echo Hello, ${{ secrets.COUNTER }}!

     
